version: '2.1'

services:
  product:
    build: microservices/product-service
    mem_limit: 200m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  recommendation:
    build: microservices/recommendation-service
    mem_limit: 200m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb

  review:
    build: microservices/review-service
    mem_limit: 200m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 200m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # $ mongo
  mongodb:
    image: mongo:4.2.2
    mem_limit: 350m
    ports:
      - "27017:27017"
    #command: mongod --smallfiles

  # $ mysql -uroot -h127.0.0.1 -p
  postgres:
    image: postgres:12.1
    mem_limit: 350m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=review_db
      - POSTGRES_USER=review_db
      - POSTGRES_PASSWORD=pwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U review_db"]
      interval: 10s
      timeout: 5s
      retries: 5
