server:
  port: 7003

# Strongly recommend to set this property to "none" in a production environment!


spring.datasource:
  url: jdbc:postgresql://localhost:5432/review_db
  username: review_db
  password: pwd

spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      initialization-fail-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    vn.com.acb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres/review_db


server:
  port: 8080
